### ISSUE TITLE
Sample app is not generating QR Codes

### ISSUE THREAD

**Issue by tom-urwin-kidsloop** [Azure-Samples/active-directory-verifiable-credentials-dotnet#17]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I have the sample app running via ngrok as per the MS guide, however the web page does not generate a QR code as mentioned in Step 5: https://docs.microsoft.com/en-gb/azure/active-directory/verifiable-credentials/verifiable-credentials-configure-verifier#run-and-test-the-sample-app

I see GET CREDENTIAL and VERIFY CREDENTIAL but when clicking on VERIFY it just takes me to a single button screen with no QR code. GET shows the same as well.

### Any log messages given by the failure
> None

### Expected/desired behavior
> QR code displayed on screen for scanning

### OS and Version?
> Windows 10 running Edge 100.0.1185.50 

### Versions
![ver creds](https://user-images.githubusercontent.com/87075427/165930004-f1db2807-5753-42ce-8f12-af1e30e5f2de.jpg)

>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mahoekst** [comment]
You might have caught us in the middle of an update to our system. If you look in your console (F12) what is the error message, or if you debug the app and break on https://github.com/Azure-Samples/active-directory-verifiable-credentials-dotnet/blob/main/1-asp-net-core-api-idtokenhint/IssuerController.cs#L48 can you see where the error occurs?

We are updating our system to get ready for our RTM release so there is some manual steps you need to go through: https://docs.microsoft.com/en-us/azure/active-directory/verifiable-credentials/verifiable-credentials-faq?#updating-the-vc-service-configuration

**Comment by tom-urwin-kidsloop** [comment]
I realise now that when clicking GET or VERIFY CREDENTIAL that ngrok is registering a 400 bad request. 

Any ideas please?

**Comment by tom-urwin-kidsloop** [comment]
Apologies just saw your response, will review.

**Comment by mahoekst** [comment]
Yes please let us know how it went. We just finished the rollout yesterday, apologies for the disruption, following the instructions at the FAQ site should help resolve any permission issues. (changing permissions on Storage might take a bit longer, Key Vault is typically quick to take)

**Comment by tom-urwin-kidsloop** [comment]
Right, I've recreated the credentials and gone through all the steps again. I've added the new variables to the appsettings.json file but I am still seeing the same behaviour.

When attempting to get a credential, I see the following exceptions in VSCode:

Exception thrown: 'Microsoft.Identity.Client.MsalServiceException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll

Cheers,
Tom

**Comment by mahoekst** [comment]
Are you able to debug? I am curious where it fails. If you are able to successfully get an access token for the API (that means correct appid, secret and security setup) or if there is an issue calling the API? (wrong payload, incorrect configuration of Key Vault)

**Comment by Karthikmuthiahr** [comment]
Hey Tom, can you please test the payload with postman and confirm if you are able to get the access token and also verify the KV permissions with the new service principals?

To troubleshoot using postman : https://github.com/Azure-Samples/active-directory-verifiable-credentials/tree/main/Postman

**Comment by tom-urwin-kidsloop** [comment]
Thanks guys. In terms of a token, no issues using same client ID and secret as VSCode:
![image](https://user-images.githubusercontent.com/87075427/167370893-34d3636e-dfc0-4acb-9493-cfdda5fd4c99.png)

Permissions look good:
![image](https://user-images.githubusercontent.com/87075427/167371001-2cbe2dfa-de70-4983-9301-7ae1e39c2a61.png)

Service Principals are there:
![image](https://user-images.githubusercontent.com/87075427/167371121-13828cd0-1b0a-4895-9f6b-2c8aec7e34f2.png)
![image](https://user-images.githubusercontent.com/87075427/167371185-a0a31d4f-436f-4dc9-9448-8ad650f88652.png)

In terms of debugging, I am running the debug console in VSCode. There were the exceptions above previously but currently I am seeing no issues.

No doubt I am missing something.

**Comment by Karthikmuthiahr** [comment]
Glad to know that currently you are not seeing any issues. Let us know if you are facing any issues in the future :)

**Comment by tom-urwin-kidsloop** [comment]
Erm no, I still have the same issue when running the code! No QR code.

I was just validating the steps you guys asked.

**Comment by Karthikmuthiahr** [comment]
Ah my bad. So in KV, access policies do you have the necessary permissions for the service principals as well?

https://docs.microsoft.com/en-us/azure/active-directory/verifiable-credentials/verifiable-credentials-configure-tenant#set-access-policies-for-the-key-vault

**Comment by tom-urwin-kidsloop** [comment]
The services have GET and SIGN and I have lots:

![image](https://user-images.githubusercontent.com/87075427/167374960-d9c18e67-9279-4c28-a0bf-4b8612241cd5.png)

Cheers

**Comment by Karthikmuthiahr** [comment]
Thanks for checking. Can you leverage the postman to do an issuance call with the access token you got?

The steps are here : https://github.com/Azure-Samples/active-directory-verifiable-credentials/tree/main/Postman

This will help to identify the missing parameters if any.

And one more question is if the appsettings.json has the right CredentialManifest and IssuerAuthority/VerifierAuthority

**Comment by tom-urwin-kidsloop** [comment]
OK, that's progress. I'm not getting past the first steps as the token is invalid:
"error":{"code":"invalid_aad_access_token","message":"No acceptable roles were found in access token, required roles are [\"VerifiableCredential.Create.All\"]."

But the API permission is added and granted as above. I just tried removing and re-adding it but no change.

Have checked and double checked the appsettings.json variables. Thanks

**Comment by tom-urwin-kidsloop** [comment]
Right, we might be getting somewhere. I have only added the new one, I guess I removed the old one. But I don't see any app with the bbb ID that I can now add?

**Comment by Karthikmuthiahr** [comment]
Got it. If that is the case, let's go with this. Can you update the scope as 3db474b9-6a0c-4840-96ac-1fceb342124f/.default and get the access token and try again please?

**Comment by tom-urwin-kidsloop** [comment]
Ah makes sense, Postman was looking under the old app. So yes, now I have a QR code in Postman! 

(Albeit a non-working one as I couldn't work out what "url" and "state" should be).

Does that reveal anything re VSCode?

**Comment by Karthikmuthiahr** [comment]
Did you update the manifest with the credential URL?

under the body of the postman request

"issuance": {
        "type": "credentialtype",
        "manifest":

**Comment by tom-urwin-kidsloop** [comment]
That I did. But further up it asks for URL and State, where do they come from? The doc suggests updating those as well. 

In any case, shouldn't it work in VSCode if I can get this far in Postman?

**Comment by Karthikmuthiahr** [comment]
If you have the necessary permissions and a working access token, it should work with VSCode. I am curious about the setup. Please let us know if you can open a quick service request and I will setup a call where we can review the setup together.

**Comment by tom-urwin-kidsloop** [comment]
Sure thing. Via MS/Azure support you mean?

**Comment by Karthikmuthiahr** [comment]
Yeah, Azure Support. Share the SR number once you raise it please.

**Comment by tom-urwin-kidsloop** [comment]
Danke 2205090050001877
