### ISSUE TITLE
Unhandled ExceptionField 'exp' is required, but it was missing.

### ISSUE THREAD

**Issue by AmitavaHazra** [Azure-Samples/active-directory-verifiable-credentials-dotnet#29]
Reference: after setting up 2-asp-net-core-api-user-signin application as per document we are having issue while adding verifiable credential in MS authenticator app.

Here, after setting up required configuration it is generating QR code and once successfully scanned it asked for manual code.
Post this once I click "Add" in authenticator app it is throwing error instead of credential added success message.
Error message in authenticator app:
Unhandled ExceptionField 'exp' is required, but it was missing.

Please help and advise.

**Comment by kocho-tomu** [comment]
Just saw this. I posted a similar bug yesterday as well

**Comment by cljung** [comment]
Closing this issue with the prev comment
