### ISSUE TITLE
Is BBS+ VC possible or will this be supported in the near future?

### ISSUE THREAD

**Issue by damienbod** [Azure-Samples/active-directory-verifiable-credentials-dotnet#3]
Thanks for the cool sample, works really good. 

Question:
Just wondering if it is possible to use BBS+ verifiable credentials?

If not possible, will this be supported by Azure AD VC anytime in the near future?

Greetings Damien

**Comment by mahoekst** [comment]
Thanks Damien, also great blogpost!. So BBS+ is not implemented, selective disclosure is planned for a future release.
