### ISSUE TITLE
IssuanceRequests is working but PresentationRequests gives an error

### ISSUE THREAD

**Issue by brijesh-1111** [Azure-Samples/active-directory-verifiable-credentials-dotnet#39]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [X] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I have created two different verifiable Ids and both of them are registered linked verified domains. (I have used two different Azure AD to register them)
> Using one of the Verified ID credentials I am getting the credential (IssuanceRequests) while using another Verified ID credential I am trying to verify (PresentationRequest).
> I am able to create the credential successfully and using the Microsoft Authenticator App, I have stored that credential in my mobile app. (I have used this repo code for that)
> While I am trying to verify that's where I am getting an issue. I am able to generate the presentation request, I am getting the barcode correctly. However, when I use my Microsoft Authenticator App to scan that barcode it says " A Generic error has occurred on the server. No Authority" I have checked the payload and It has authority and that is the registered domain starts with did:web:....  

### Any log messages given by the failure
> I am getting the log from Microsoft Authenticator App while I scan the presentation request is:
"Error Details: A generic error has occurred on the server."
> After an upgrade to new version of Authenticator App I am getting new error. It says:
"Failed to send request. Unable to resolve host "beta.did.msidentity.com": No address associated with hostname."
> During the troubleshooting activity, I found another version. It says
" A Generic error has occurred on the server. No Authority"

### Expected/desired behavior
> I was expecting that it will read my existing credentials stored in my App and suggest me which one to use and I select that and It will send that to verify.

### OS and Version?
> Windows 10

### Versions
> .Net Core 6

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by brijesh-1111** [comment]
I have posted the issue in StackOverflow with detail error logs in case that helps someone troubleshoot it further.
https://stackoverflow.com/questions/74511252/verifiable-credential-presentation-request-gives-an-internal-server-error

**Comment by savvush** [comment]
Check issue #40, its probably applicable for you as well.

**Comment by brijesh-1111** [comment]
Nope. I do not think that is similar to issue #40. The reason it is different is here.
After I scan the QR Code through my mobile, I am expecting the callback on the PresentationCallback function but before that itself I am getting an error on my mobile. (I have a breakpoint and it did not get hit) above error message is coming in my Mobile,

Again steps are:

1. I am generating my presentation request through the code in this sample
2. I am getting QR Code. I use my mobile with Microsoft Authenticator App and scan that code
3. I already have an Issuer card previously stored (same organization as the presentation/verification request).
4. Because the Authenticator app finds that I have the card saved which can be used against presentation requests, It offers me to use that.
5. I click the shred button in Authenticator App and boom. I get an error. 
6. I do not get the breakpoint hit on PresentationCallback function.

**Comment by brijesh-1111** [comment]
Nope. I do not think that is similar to issue https://github.com/Azure-Samples/active-directory-verifiable-credentials-dotnet/issues/40. The reason it is different is here.
After I scan the QR Code through my mobile, I am expecting the callback on the PresentationCallback function but before that itself I am getting an error on my mobile. (I have a breakpoint and it did not get hit) above error message is coming in my Mobile,

Again steps are:

I am generating my presentation request through the code in this sample
I am getting QR Code. I use my mobile with Microsoft Authenticator App and scan that code
I already have an Issuer card previously stored (same organization as the presentation/verification request).
Because the Authenticator app finds that I have the card saved which can be used against presentation requests, It offers me to use that.
I click the shred button in Authenticator App and boom. I get an error.
I do not get the breakpoint hit on PresentationCallback function.

**Comment by bolt-io** [comment]
Hi @brijesh-1111

we encountered an error that seems to be the same as the one you are encountering. 
This was ultimately resolved by using ngrok and ensuring that the [presentation_request_config.json](../tree/main/1-asp-net-core-api-idtokenhint/presentation_request_config.json) was up to date with the configuration from our verified ID service and our new temporary ngrok URL for the `callback:url` setting.

Solution in collaboration with [manalawad84](https://github.com/manalawad84)

**Comment by cljung** [comment]
Closing old issues as sample is updated
