### ISSUE TITLE
Second Sample - PresentationCallback of VC fails

### ISSUE THREAD

**Issue by savvush** [Azure-Samples/active-directory-verifiable-credentials-dotnet#40]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Just configure the second sample and try to present the VC that was issued. You'll get an error on the Authenticator app and diagnosis information on the Authenticator app doesn't give you a hint about the issue. I debugged the sample and it looks like the line on 224 (on VerifierController.cs) is causing the issue. e.g. //payload = presentationResponse["issuers"].ToString(),

According the ngrok, the callback URL receives the following data

![payload](https://user-images.githubusercontent.com/6704044/205083674-f3937215-46de-4f06-aabd-d97be470ffe3.png)

which doesn't have a key with "issuers", so I commented out this line. Instead, one can also use 
payload =  presentationResponse["verifiedCredentialsData"][0]["issuer"].

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by cljung** [comment]
Closing old issues as sample is updated
