### ISSUE TITLE
Android deeplink not working

### ISSUE THREAD

**Issue by damienbod** [Azure-Samples/active-directory-verifiable-credentials-dotnet#47]
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

Login on Android phone and wait for the timeout

### Expected/desired behavior
Flow completes on phone using deeplink

The follow code causes the issue
´´´
 window.location.href = respPresentationReq.url;
setTimeout(function () {
    window.location.href = "https://play.google.com/store/apps/details?id=com.azure.authenticator";
}, 2000);
´´´

Fix: remove the setTimeout function. It would be nice to keep the timeout, but the 2s is not long enough as well.

´´´
 window.location.href = respPresentationReq.url;
´´´

I could create a PR to remove this if you want

Greetings Damien

**Comment by cljung** [comment]
Deep link should be fixed in the new version of the sample.

**Comment by damienbod** [comment]
Thanks, I'll test
