### ISSUE TITLE
Close Microsoft Authenticator app (Android) and return to browser

### ISSUE THREAD

**Issue by damienbod** [Azure-Samples/active-directory-verifiable-credentials-dotnet#48]
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

On an Android phone, when I complete the presentation flow using the deeplink, the Microsoft Authenticator app does not close and the user is NOT returned to the browser.

How can I close the Microsoft Authenticator app and return the user to the browser?

Code:

´´´
window.location.href = respPresentationReq.url;
´´´

Greetings Damien

**Comment by cljung** [comment]
You have to use the back button top right corner to return to the previous app
Closing old issues as sample is updated
