### ISSUE TITLE
Issue with tenant callback

### ISSUE THREAD

**Issue by AmitavaHazra** [Azure-Samples/active-directory-verifiable-credentials-dotnet#49]
Reference ,
https://github.com/Azure-Samples/active-directory-verifiable-credentials-dotnet/tree/main/2-asp-net-core-api-user-signin

While using this id token-based sample, it fails in verifier solution.
Error Message,
A generic error has occured on the server. Error while calling tenant callback : bad request.

@cljung , can you please suggest.

BR,
Amitava

**Comment by cljung** [comment]
@AmitavaHazra sample 2- will be updated shortly

**Comment by cljung** [comment]
closing this due to age
