### ISSUE TITLE
What is the use of the TenantObiectId="b6c11183-fc66-xxxx-xxxx-xxxxxxxxxxxx" in the refreshed B2C policies?

### ISSUE THREAD

**Issue by SB-o-matic** [Azure-Samples/active-directory-verifiable-credentials-dotnet#63]

**Comment by cljung** [comment]
@SB-o-matic It returns the current tenantId that is being used. See docs on [claim resolver](https://learn.microsoft.com/en-us/azure/active-directory-b2c/claim-resolver-overview#policy)
