### ISSUE TITLE
Managed Identity not working - "Provided access token contains no roles"

### ISSUE THREAD

**Issue by SB-o-matic** [Azure-Samples/active-directory-verifiable-credentials-dotnet#65]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
1. Set managed identity to true when deploying the web app
2. Run provided powershell to grant managed identity application permissions to the verifiable credentials service
3. Attempt to issue a credential
4. error seen in dev tools "Provided access token contains no roles"

I had to switch to using an app registration with a credential. When I did that, error "_Provided access token contains no roles_" went away. But got another - "_Something went wrong calling the API..Expiration Date cannot be used when Validity Interval is not allowed to be overridden._" Opened a different issue for that here -  https://github.com/Azure-Samples/active-directory-verifiable-credentials-dotnet/issues/64.

Note that I even tried to reapply the permissions by running the powershell again but got an error that mentioned the permissions are already applied. But ran Get-AzureADServiceAppRoleAssignment on the managed identity and it returned nothing. Might try an MG-Graph cmdlet later.
### Any log messages given by the failure
>
"Provided access token contains no roles"
### Expected/desired behavior
>
Successful call to the VC request service
### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Win 11
### Versions
>
22H2
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by SB-o-matic** [comment]
A not that I am running the Azure B2C sample (3).

**Comment by cljung** [comment]
1. Sounds like your app permission assignment to the MSI identity didn't work. Please check that your specified the correct appname and objectId.
2. The Expiration Date error is due to not having updated the contract to allow it to be updated. Either update setting `VerifiedID__CredentialExpiration` to an empty string or update the contract to allow it. See [docs](https://learn.microsoft.com/en-us/entra/verified-id/whats-new#february-2024)

**Comment by cljung** [comment]
@SB-o-matic regarding "Provided access token contains no roles". Your MSI assignment didn't work and the access token you used does not contain the VerifiableCredentials.Create.All permission
