### ISSUE TITLE
Needs Clarification - "You do not need to register an app or create a custom Verified ID credential schema."

### ISSUE THREAD

**Issue by SB-o-matic** [Azure-Samples/active-directory-verifiable-credentials-dotnet#66]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
n/a
### Any log messages given by the failure
>
n/a
### Expected/desired behavior
>
I am running the Azure B2C sample.
Clarification stating how the credential is accounted for if there is no need to create one any longer in the portal (or by other means) prior to running the samples. In previous samples (editions) display and rules files were provided which I have used as a guide when creating the credential in the portal that matches the credential type the sample expects. If this is no longer needed, will the latest version of this sample be creating this for us going forward? If that is the case, how will one fill in the manifest url when deploying the sample using the ARM template in the README (Deploy to Azure)? Also, the 'My Account' experience referenced in the README is only available of type Verified Employee, which does not align with a typical B2C use case
### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Win 11
### Versions
>
21H2
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by cljung** [comment]
The steps for creating an account and issuing a credential is mentioned in the README's [setup section](https://github.com/Azure-Samples/active-directory-verifiable-credentials-dotnet/tree/main/3-asp-net-core-api-b2c#using-the-sample). 
1. Click Sign-in, then sign-up for creating a local account
2. Select Issue Credential from home page

- The manifestURL is one of the parameters you need to fill in during ARM template deployment (parameter `CredentialManifest`).
- My Account and VerifiedEmployee isn't used or mentioned in the B2C sample
