### ISSUE TITLE
Needs Clarification - "Note that Verified ID can not be onboarded in the B2C tenant as that is not supported." Yes but....

### ISSUE THREAD

**Issue by SB-o-matic** [Azure-Samples/active-directory-verifiable-credentials-dotnet#67]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
n/a
### Any log messages given by the failure
>
n/a
### Expected/desired behavior
>
When you create an Azure AD B2C resource, it comes with an Entra ID instance. You can see this when from the Home page you search for Entra ID (be sure your selected directory remains the Azure B2C directory). In This Entra ID instance, I can add a custom domain. Then I can go to Security => Verified ID and setup Verified ID with the Quick setup. It is not looking any different (so far) from using a regular Entra ID tenant. Is it then correct to say that we can use this B2C-associated Entra ID as a VC issuer and Verifier?
### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Win 11
### Versions
>
21H2
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by cljung** [comment]
It is not supported by Entra Verified ID to be onboarded to a B2C tenant
