### ISSUE TITLE
Subproject nº3 - error custom B2C XML upload Azure

### ISSUE THREAD

**Issue by mcutanda-kpmg** [Azure-Samples/active-directory-verifiable-credentials-dotnet#82]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I am following the guide provided in this GitHub (https://github.com/Azure-Samples/active-directory-verifiable-credentials-dotnet/blob/main/3-asp-net-core-api-b2c/B2C/README.md#setup). I have configured the B2C Tenant, configured and uploaded to the B2C the "B2C Custom Policy Starter Pack - LocalAccounts"; also the REST API, the web application...

> The problem is that I have configured the B2C Custom Policies, and I have uploaded them to the "Identity Experience Framework" section of Azure, but the XML of "SignUpOrSignInVCQ.xml" and "SignUpVCOrSignin.xml", I get an error.

> Question: the 6 custom policies (https://github.com/Azure-Samples/active-directory-verifiable-credentials-dotnet/tree/main/3-asp-net-core-api-b2c/B2C/policies), do they have to be uploaded all 6 to Azure, to work properly?

### Any log messages given by the failure
**SignUpOrSignInVCQ.xml**
> Validation failed: 5 validation error(s) found in policy "B2C_1A_VC_SUSIQ" of tenant "xxxxxx.onmicrosoft.com".User journey 'SignUpOrSignIn' in policy 'B2C_1A_VC_susiq' of tenant 'xxxxxx.onmicrosoft.com' has 2 sendClaims steps. Please specify a DefaultCpimIssuerTechnicalProfileReferenceId attribute set to the default issuer technical profile reference id.User Journey "SignUpOrSignIn" in policy "B2C_1A_VC_susiq" of tenant "xxxxxx.onmicrosoft.com" was expected to have step with order "5" but it was not found.User Journey "SignUpOrSignIn" in policy "B2C_1A_VC_susiq" of tenant "xxxxxx.onmicrosoft.com" was expected to have step with order "6" but it was not found.
User Journey "SignUpOrSignIn" in policy "B2C_1A_VC_susiq" of tenant "xxxxxx.onmicrosoft.com" was expected to have step with order "5" but it was not found.User Journey "SignUpOrSignIn" in policy "B2C_1A_VC_susiq" of tenant "xxxxxx.onmicrosoft.com" was expected to have step with order "6" but it was not found.User journey 'SignUpOrSignIn' in policy 'B2C_1A_VC_susiq' of tenant 'xxxxxx.onmicrosoft.com' has 2 sendClaims steps. Please specify a DefaultCpimIssuerTechnicalProfileReferenceId attribute set to the default issuer technical profile reference id.User Journey "SignUpOrSignIn" in policy "B2C_1A_VC_susiq" of tenant "xxxxxx.onmicrosoft.com" was expected to have step with order "5" but it was not found.User Journey "SignUpOrSignIn" in policy "B2C_1A_VC_susiq" of tenant "xxxxxx.onmicrosoft.com" was expected to have step with order "6" but it was not found.User Journey "SignUpOrSignIn" in policy "B2C_1A_VC_susiq" of tenant "xxxxxx.onmicrosoft.com" was expected to have step with order "5" but it was not found.User Journey "SignUpOrSignIn" in policy "B2C_1A_VC_susiq" of tenant "xxxxxx.onmicrosoft.com" was expected to have step with order "6" but it was not found.

**SignUpVCOrSignin.xml**
> Validation failed: 5 validation error(s) found in policy "B2C_1A_VC_SUSI_ISSUEVC" of tenant "xxxxxx.onmicrosoft.com".User journey 'SignUpOrSignIn' in policy 'B2C_1A_VC_susi_issuevc' of tenant 'xxxxxx.onmicrosoft.com' has 2 sendClaims steps. Please specify a DefaultCpimIssuerTechnicalProfileReferenceId attribute set to the default issuer technical profile reference id.User Journey "SignUpOrSignIn" in policy "B2C_1A_VC_susi_issuevc" of tenant "xxxxxx.onmicrosoft.com" was expected to have step with order "5" but it was not found.User Journey "SignUpOrSignIn" in policy "B2C_1A_VC_susi_issuevc" of tenant "xxxxxx.onmicrosoft.com" was expected to have step with order "6" but it was not found.User Journey "SignUpOrSignIn" in policy "B2C_1A_VC_susi_issuevc" of tenant "xxxxxx.onmicrosoft.com" was expected to have step with order "5" but it was not found.User Journey "SignUpOrSignIn" in policy "B2C_1A_VC_susi_issuevc" of tenant "xxxxxx.onmicrosoft.com" was expected to have step with order "6" but it was not found.User journey 'SignUpOrSignIn' in policy 'B2C_1A_VC_susi_issuevc' of tenant 'xxxxxx.onmicrosoft.com' has 2 sendClaims steps. Please specify a DefaultCpimIssuerTechnicalProfileReferenceId attribute set to the default issuer technical profile reference id.User Journey "SignUpOrSignIn" in policy "B2C_1A_VC_susi_issuevc" of tenant "xxxxxx.onmicrosoft.com" was expected to have step with order "5" but it was not found.User Journey "SignUpOrSignIn" in policy "B2C_1A_VC_susi_issuevc" of tenant "xxxxxx.onmicrosoft.com" was expected to have step with order "6" but it was not found.User Journey "SignUpOrSignIn" in policy "B2C_1A_VC_susi_issuevc" of tenant "xxxxxx.onmicrosoft.com" was expected to have step with order "5" but it was not found.User Journey "SignUpOrSignIn" in policy "B2C_1A_VC_susi_issuevc" of tenant "xxxxxx.onmicrosoft.com" was expected to have step with order "6" but it was not found.

### Expected/desired behavior
> Upload the 6 custom policies to the "Identity Experience Framework" section of Azure, without errors.

### OS and Version?
> I'm running this in the Web app, in Azure.

### Versions
> DotNet v6

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by cljung** [comment]
@mcutanda-kpmg - what version of the IEF Custom Policy Starter pack are you using? LocalAccount, SocialAndLocal or SocialAndLocal+MFA?

**Comment by mcutanda-kpmg** [comment]
Thanks for getting involved in the post I created.
As I said in the post, I am using the “B2C Custom Policy Starter Pack - LocalAccounts”.
If you have any other questions or concerns feel free to contact me.

**Comment by mcutanda-kpmg** [comment]
@cljung I'm sorry to bother you, but is there any news on this topic?

**Comment by mcutanda-kpmg** [comment]
Now everything works properly, thank you very much for the help!

**Comment by mcutanda-kpmg** [comment]
@cljung Sorry to bother you again, but were you able to read my last comment? 
If it is better for you we can discuss it in a new issue.
