### ISSUE TITLE
Subproject nº3 - Error claims exchange 'REST-VC-GetAuthResult'

### ISSUE THREAD

**Issue by mcutanda-kpmg** [Azure-Samples/active-directory-verifiable-credentials-dotnet#85]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Following the project guide number 3 and having deployed the “B2C Custom Policy Starter Pack - LocalAccounts” policies, I have deployed the web app in Azure correctly: I can do the login, Issue Credential and Verifiy Credential correctly. 

### Any log messages given by the failure
> When I want to login using the QR and I present a valid card, I get this error:
`The claims exchange 'REST-VC-GetAuthResult' specified in step '2' returned HTTP error response with Code 'BadRequest' and Reason 'Bad Request'.` I think it is a issue with the “TrustFrameworkExtensionsVC.xml” policy.

> Also, when you Sign Out, it redirects to a blank page instead of the Home page.

### Expected/desired behavior
> Login to the web app with the QR of the VC.

### OS and Version?
> I'm running this in the Web app, in Azure.

### Versions
> DotNet v6

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mcutanda-kpmg** [comment]
Hi, at the end the error of “REST-VC-GetAuthResult”, was because of the Api Key in the tenant B2C. In the first version of a few days ago, as it was not indicated in the guide, I generated this key automatically; but having created it again manually, it works.

On the other hand, have you been able to check the Sign out?

**Comment by cljung** [comment]
It is mentioned in the README that you need to manually set the RestApiKey in 4th bullet [here](https://github.com/Azure-Samples/active-directory-verifiable-credentials-dotnet/tree/main/3-asp-net-core-api-b2c/B2C#setup)
