### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by janschw-sftp** [Azure-Samples/active-directory-verifiable-credentials-dotnet#86]
Hello, 
I'm getting the following error
"Error reading assets file: Error loading lock file 'C:\home\site\repository\6-woodgrove-helpdesk\obj\project.assets.json' : Could not load file or assembly 'System.Text.Json, Version=8.0.0.4, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. **The system cannot find the file specified**. [C:\home\site\repository\6-woodgrove-helpdesk\WoodgroveHelpdesk.csproj]"

**Comment by cljung** [comment]
Issue was that App Service dotnet build engine now runs with net9 which samples weren't created for. Bumped all csproj net fx versions to net8.0 and added a global.json file to force App Service build engine to run on net8.
Thanks for reporting @janschw-sftp
